In [1]:
import numpy as np
import pandas as pd

In [10]:
original_df = pd.read_csv("Crop_recommendation.csv")
crop = pd.DataFrame(original_df)
crop


Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0           90          42         43    20.879744  82.002744  6.502985   
1           85          58         41    21.770462  80.319644  7.038096   
2           60          55         44    23.004459  82.320763  7.840207   
3           74          35         40    26.491096  80.158363  6.980401   
4           78          42         42    20.130175  81.604873  7.628473   
...        ...         ...        ...          ...        ...       ...   
2195       107          34         32    26.774637  66.413269  6.780064   
2196        99          15         27    27.417112  56.636362  6.086922   
2197       118          33         30    24.131797  67.225123  6.362608   
2198       117          32         34    26.272418  52.127394  6.758793   
2199       104          18         30    23.603016  60.396475  6.779833   

        rainfall   label  
0     202.935536    rice  
1     226.655537    rice  
2     263.964248    rice  
3     242.864034    rice  
4     262.717340    rice  
...          ...     ...  
2195  177.774507  coffee  
2196  127.924610  coffee  
2197  173.322839  coffee  
2198  127.175293  coffee  
2199  140.937041  coffee  

[2200 rows x 8 columns]

In [11]:
x=crop.drop('label',axis=1)
x

Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0           90          42         43    20.879744  82.002744  6.502985   
1           85          58         41    21.770462  80.319644  7.038096   
2           60          55         44    23.004459  82.320763  7.840207   
3           74          35         40    26.491096  80.158363  6.980401   
4           78          42         42    20.130175  81.604873  7.628473   
...        ...         ...        ...          ...        ...       ...   
2195       107          34         32    26.774637  66.413269  6.780064   
2196        99          15         27    27.417112  56.636362  6.086922   
2197       118          33         30    24.131797  67.225123  6.362608   
2198       117          32         34    26.272418  52.127394  6.758793   
2199       104          18         30    23.603016  60.396475  6.779833   

        rainfall  
0     202.935536  
1     226.655537  
2     263.964248  
3     242.864034  
4     262.717340  
...          ...  
2195  177.774507  
2196  127.924610  
2197  173.322839  
2198  127.175293  
2199  140.937041  

[2200 rows x 7 columns]

In [12]:
y=crop['label']
y

0         rice
1         rice
2         rice
3         rice
4         rice
         ...  
2195    coffee
2196    coffee
2197    coffee
2198    coffee
2199    coffee
Name: label, Length: 2200, dtype: object

In [13]:
crop.dropna(inplace=True)
crop

Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0           90          42         43    20.879744  82.002744  6.502985   
1           85          58         41    21.770462  80.319644  7.038096   
2           60          55         44    23.004459  82.320763  7.840207   
3           74          35         40    26.491096  80.158363  6.980401   
4           78          42         42    20.130175  81.604873  7.628473   
...        ...         ...        ...          ...        ...       ...   
2195       107          34         32    26.774637  66.413269  6.780064   
2196        99          15         27    27.417112  56.636362  6.086922   
2197       118          33         30    24.131797  67.225123  6.362608   
2198       117          32         34    26.272418  52.127394  6.758793   
2199       104          18         30    23.603016  60.396475  6.779833   

        rainfall   label  
0     202.935536    rice  
1     226.655537    rice  
2     263.964248    rice  
3     242.864034    rice  
4     262.717340    rice  
...          ...     ...  
2195  177.774507  coffee  
2196  127.924610  coffee  
2197  173.322839  coffee  
2198  127.175293  coffee  
2199  140.937041  coffee  

[2200 rows x 8 columns]

In [14]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
crop['label']=lb.fit_transform(crop['label'])
crop

Nitrogen  phosphorus  potassium  temperature   humidity        ph  \
0           90          42         43    20.879744  82.002744  6.502985   
1           85          58         41    21.770462  80.319644  7.038096   
2           60          55         44    23.004459  82.320763  7.840207   
3           74          35         40    26.491096  80.158363  6.980401   
4           78          42         42    20.130175  81.604873  7.628473   
...        ...         ...        ...          ...        ...       ...   
2195       107          34         32    26.774637  66.413269  6.780064   
2196        99          15         27    27.417112  56.636362  6.086922   
2197       118          33         30    24.131797  67.225123  6.362608   
2198       117          32         34    26.272418  52.127394  6.758793   
2199       104          18         30    23.603016  60.396475  6.779833   

        rainfall  label  
0     202.935536     20  
1     226.655537     20  
2     263.964248     20  
3     242.864034     20  
4     262.717340     20  
...          ...    ...  
2195  177.774507      5  
2196  127.924610      5  
2197  173.322839      5  
2198  127.175293      5  
2199  140.937041      5  

[2200 rows x 8 columns]

In [15]:
x=crop.drop('label',axis=1)
x
y=crop['label']
y

0       20
1       20
2       20
3       20
4       20
        ..
2195     5
2196     5
2197     5
2198     5
2199     5
Name: label, Length: 2200, dtype: int32

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)



In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(n_estimators= 100,max_depth=5, criterion="entropy")
classifier.fit(x_train, y_train)
x_pred=classifier.predict(x_train)
y_pred=classifier.predict(x_test)


In [18]:
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score
mean=mean_squared_error(y_train,x_pred)
r2=r2_score(y_train,x_pred)*100
r2


97.75311370291102

In [19]:
mean=mean_squared_error(y_test,y_pred)*100
r2=r2_score(y_test,y_pred)
pred=classifier.predict(x_test)
pred

array([21, 21,  7,  3,  2, 20, 13,  9, 15,  1, 13,  5, 10, 14, 12,  0,  5,
       10,  5, 12,  4,  2,  9,  8,  6,  5, 10, 16, 13,  9, 19, 20, 11, 15,
        4,  6, 12, 12, 21,  2, 11,  2, 18, 21, 18, 14,  9,  9,  6, 14, 13,
        2,  0, 15, 18,  1, 17, 12, 10,  6, 16, 14, 21, 20, 15,  0,  7,  5,
        0, 16,  4, 19,  9, 11,  7, 13,  3, 11,  8, 12, 20,  2, 21, 21, 15,
        6, 11, 10, 13, 17,  2,  8, 14,  7, 14, 11,  5,  8, 10,  3, 16,  8,
       14,  1,  1, 20, 21,  5, 18, 15, 15, 12,  5,  7, 16, 19, 14, 10, 11,
        8, 19, 10, 16,  3,  3,  2, 19, 16,  3, 17, 13, 13, 15, 14, 11, 14,
        4, 19, 16,  2,  2,  7,  0,  5,  3,  0,  8, 12, 21, 17, 16,  4, 13,
        1, 19,  3, 21,  2,  0,  8, 10, 18,  8,  9,  9, 15, 20, 15,  1, 16,
       18,  0, 13,  4,  6, 14,  9, 19, 17, 16, 20, 17, 17, 18,  9,  1,  4,
       18, 20, 17, 11,  8, 13, 20, 11,  5, 18,  4,  3, 12,  4, 19, 11, 13,
       13, 16, 15, 11, 18,  1,  3,  2, 18, 16, 13, 14, 12, 17, 15, 19,  8,
       20,  2, 17,  2,  5

In [20]:
ac=accuracy_score(y_test,y_pred)
ac*100

98.7878787878788

In [21]:
pred=classifier.predict([[90,42,43,20.879744,82.002744,6.502985,202.935536]])
pred

c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([20])

In [22]:
pred1=classifier.predict([[118,33,30,24.131797,67.225123,6.362608,173.322839]])
pred1


c:\ProgramData\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([5])

In [23]:
from joblib import dump

In [24]:
dump(classifier, 'classifier.pkl')

['classifier.pkl']